services:
  app:
    environment:
      - MODE=dev
      - GIN_MODE=debug
    profiles:
      - app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    profiles:
      - adminer
