services:
  app:
    build: .
    env_file: .env
    environment:
      - MODE=prod
      - GIN_MODE=release
      - DB_HOST=db
      - CURRENCY_API_URL=http://mock-api:8000
    ports:
      - 8000:8000

  mock-api:
    build: .mock-api
    ports:
      - 8010:8000

  db:
    image: postgres:13
    restart: always
    shm_size: 128mb
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - .db-data:/var/lib/postgresql/data
